-- AlterTable
ALTER TABLE `AssistenciaDistribuidoOficial` ADD COLUMN `origem` ENUM('PLANILHA', 'CONFIGURADO') NOT NULL DEFAULT 'CONFIGURADO';

-- AlterTable
ALTER TABLE `CusteioDistribuidoOficial` ADD COLUMN `origem` ENUM('PLANILHA', 'CONFIGURADO') NOT NULL DEFAULT 'CONFIGURADO';

-- AlterTable
ALTER TABLE `EficienciaAcademicaAnual` ADD COLUMN `origem` ENUM('PLANILHA', 'CONFIGURADO') NOT NULL DEFAULT 'CONFIGURADO';

-- AlterTable
ALTER TABLE `MatriculaTotalEqualizadaAnual` ADD COLUMN `origem` ENUM('PLANILHA', 'CONFIGURADO') NOT NULL DEFAULT 'CONFIGURADO';

-- AlterTable
ALTER TABLE `RappAnual` ADD COLUMN `origem` ENUM('PLANILHA', 'CONFIGURADO') NOT NULL DEFAULT 'CONFIGURADO';
