export type PnpFileType =
  | "DADOS_GERAIS"
  | "EFICIENCIA_ACADEMICA"
  | "RELACAO_ALUNO_PROFESSOR_RAP"
  | "PERCENTUAIS_LEGAIS"
  | "CLASSIFICACAO_RACIAL_RENDA_SEXO"
  | "SITUACAO_MATRICULA";

export const PNP_FILE_TYPES: readonly PnpFileType[] = [
  "DADOS_GERAIS",
  "EFICIENCIA_ACADEMICA",
  "RELACAO_ALUNO_PROFESSOR_RAP",
  "PERCENTUAIS_LEGAIS",
  "CLASSIFICACAO_RACIAL_RENDA_SEXO",
  "SITUACAO_MATRICULA",
];
