export type PnpFileType =
  | "DADOS_GERAIS"
  | "SITUACAO_MATRICULA"
  | "CLASSIFICACAO_RACIAL_RENDA_SEXO"
  | "PERCENTUAIS_LEGAIS"
  | "RESERVA_VAGAS"
  | "OFERTA_VAGAS_NOTURNAS"
  | "RELACAO_INSCRITOS_VAGAS"
  | "TAXA_EVASAO"
  | "EFICIENCIA_ACADEMICA"
  | "RELACAO_ALUNO_PROFESSOR_RAP"
  | "INDICE_VERTICALIZACAO"
  | "TAXA_OCUPACAO"
  | "PROFESSORES_POR_INSTITUICAO"
  | "TECNICOS_ADM_NIVEL"
  | "TITULACAO_DOCENTE"
  | "INDICADORES_GASTOS"
  | "PANORAMA_ORCAMENTARIO"
  | "CARGOS_CARREIRA";

export const PNP_FILE_TYPES: readonly PnpFileType[] = [
  "DADOS_GERAIS",
  "SITUACAO_MATRICULA",
  "CLASSIFICACAO_RACIAL_RENDA_SEXO",
  "PERCENTUAIS_LEGAIS",
  "RESERVA_VAGAS",
  "OFERTA_VAGAS_NOTURNAS",
  "RELACAO_INSCRITOS_VAGAS",
  "TAXA_EVASAO",
  "EFICIENCIA_ACADEMICA",
  "RELACAO_ALUNO_PROFESSOR_RAP",
  "INDICE_VERTICALIZACAO",
  "TAXA_OCUPACAO",
  "PROFESSORES_POR_INSTITUICAO",
  "TECNICOS_ADM_NIVEL",
  "TITULACAO_DOCENTE",
  "INDICADORES_GASTOS",
  "PANORAMA_ORCAMENTARIO",
  "CARGOS_CARREIRA",
];
