-- AlterTable
ALTER TABLE `CalculationResult` MODIFY `bloco` ENUM('FUNCIONAMENTO', 'REITORIAS', 'QUALIDADE_EFICIENCIA', 'ASSISTENCIA_ESTUDANTIL', 'ANUIDADE_CONIF') NOT NULL;

-- AlterTable
ALTER TABLE `OrcamentoAnual` ADD COLUMN `percentualAnuidade` DECIMAL(7, 4) NOT NULL DEFAULT 0;
